name: Automate Issues
on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install PyGithub

      - name: Executar script de Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python github_manager.py
